### PR TITLE
add ARGB and BGRA to supported sink caps

### PR DESCRIPTION
**Pull request by wangzj0601**
Signed-off-by: Wang Zhanjun <zhanjunx.wang@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
LGTM.

@ceyusa can you review?  thanks.

**Comment by uartie** [comment]
@ceyusa would it be better if we just fork and maintain our own version?  Our https://github.com/intel/vaapi-fits project depends on checksumsink2 from here.

**Comment by uartie** [comment]
Output files look correct with the following commands:
```
$ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=BGRA,width=720,height=480 \
  ! checksumsink2 dump-output=true dump-location=output-720x480-BGRA.rgb

$ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=ARGB,width=720,height=480 \
  ! checksumsink2 dump-output=true dump-location=output-720x480-ARGB.rgb
```

However, when using vaapipostproc, ARGB command fails (BGRA works):
```
$ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=NV12,width=720,height=480 \
  ! vaapipostproc format=argb \
  ! checksumsink2 dump-output=true dump-location=output-720x480-vpp-ARGB.rgb
...
ERROR       vaapivideomemory gstvaapivideomemory.c:1215:gst_vaapi_dmabuf_allocator_new: failed to create a new surface
...
```

@ceyusa any clues why ARGB would fail here?

**Comment by uartie** [comment]
And if we use filesink instead of checksumsink2:
```
$ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=NV12,width=720,height=480 \
  ! vaapipostproc format=argb \
  ! filesink location=output-720x480-vpp-ARGB.rgb
```
... it dumps as RGBA, not ARGB!

**Comment by uartie** [comment]
Nonetheless, the issue is unrelated to this patch, afaict.   So, again, LGTM.

**Comment by ceyusa** [comment]
> And if we use filesink instead of checksumsink2:
> 
> ```
> $ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
>   ! video/x-raw,format=NV12,width=720,height=480 \
>   ! vaapipostproc format=argb \
>   ! filesink location=output-720x480-vpp-ARGB.rgb
> ```
> ... it dumps as RGBA, not ARGB!

Hi @uartie 

I was on vacations backpacking Vietnam. Just arrived today and I'm slowly taking the open tasks.

Could you open a bug in gstreamer-vaapi for this issue, please?

**Comment by uartie** [comment]
> > And if we use filesink instead of checksumsink2:
> > ```
> > $ gst-launch-1.0 -vf videotestsrc num-buffers=10 \
> >   ! video/x-raw,format=NV12,width=720,height=480 \
> >   ! vaapipostproc format=argb \
> >   ! filesink location=output-720x480-vpp-ARGB.rgb
> > ```
> > ... it dumps as RGBA, not ARGB!
> 
> Hi @uartie
> 
> I was on vacations backpacking Vietnam. Just arrived today and I'm slowly taking the open tasks.
> 
> Could you open a bug in gstreamer-vaapi for this issue, please?

https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/142

**Pull request merged**
